### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'renderer'

### ISSUE THREAD

**Issue by Koloz** [insula1701/maxpress#4]
[+] 正在导入配置文件... 导入成功
[+] 正在编译CSS样式表... 编译成功
[+] 正在转换example1.md... Traceback (most recent call last):
  File "/Users/a/PycharmProjects/maxpress/maxpress.py", line 216, in <module>
    convert_all()
  File "/Users/a/PycharmProjects/maxpress/maxpress.py", line 176, in convert_all
    result = md2html(text, styles,
  File "/Users/a/PycharmProjects/maxpress/maxpress.py", line 54, in md2html
    md = Markdown()
TypeError: __init__() missing 1 required positional argument: 'renderer'

**Comment by YuFeng128** [comment]
mistune库的版本原因，可以回退到0.7.4。或者自己修改代码
```powershell
pip install -U mistune==0.7.4
```
